### ISSUE TITLE
Required detailed directions

### ISSUE THREAD

**Issue by anjalibhavan** [stevezheng23/language_model_tf#25]
Hello,
Can you please provided instructions (preferably in the readme.md file) as to how to run this in my system - that is, which file to run first, where to give inputs etc?
Thanks!

**Comment by stevezheng23** [comment]
This project is currently under testing, corresponding usage instruction will be added once testing is done. Thanks!

**Comment by stevezheng23** [comment]
Basic description is added @anjalibhavan
